export default {
    ADD_TODO_FAIL:"ADD_TODO_FAIL",
    ADD_TODO_REQUEST:"ADD_TODO_REQUEST",
    ADD_TODO_SUCCESS:"ADD_TODO_SUCCESS",

    REMOVE_TODO:"REMOVE_TODO",
    COMPLETE_TODO:"COMPLETE_TODO",
    USER_LOG_OUT:"USER_LOG_OUT", 
    OPEN_NOTE_FORM:"OPEN_NOTE_FORM",
    CLOSE_NOTE_FORM:"CLOSE_NOTE_FORM",
    TOGGLE_NOTE_FORM:"TOGGLE_NOTE_FORM",
    
    LIST_TODOS_SUCCESS:"LIST_TODOS_SUCCESS", 
    LIST_TODOS_FAIL:"LIST_TODOS_FAIL",
    LIST_TODOS_REQUEST:"LIST_TODOS_REQUEST",

    USER_SIGNIN_SUCCESS:"USER_SIGNIN_SUCCESS", 
    USER_SIGNIN_FAIL:"USER_SIGNIN_FAIL",
    USER_SIGNIN_REQUEST:"USER_SIGNIN_REQUEST",

    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS", 
    USER_REGISTER_FAIL:"USER_REGISTER_FAIL",
    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST"
}